### ISSUE TITLE
Investigate context-sensitive keywords instead of virtual and override.

### ISSUE THREAD

**Issue by atomgalaxy** [atomgalaxy/wg21-cust-points#23]
As per ville.

**Comment by lewissbaker** [comment]
The branch https://github.com/atomgalaxy/wg21-cust-points/tree/corentin/update_syntax now contains context-sensitive `customisable` keyword instead of `virtual` keyword.

**Comment by lewissbaker** [comment]
R1 added the use of `customisable` trailing keyword instead of `virtual`
