### ISSUE TITLE
Incomplete sentence in "Unable to customise different ADL names generically"

### ISSUE THREAD

**Issue by lewissbaker** [atomgalaxy/wg21-cust-points#27]
Page 14.
> This means we cannot build wrapper types that generically customise and forward on multiple customisation
point calls to a child object. We need to explicitly customise and forward on the calls for each ADL name. This
necessitates

Sentence is cutoff at end.

Thanks to Lee for pointing this out.

**Comment by cor3ntin** [comment]
This was already fixed by @atomgalaxy
